// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package v1_test is a generated GoMock package.
package v1_test

import (
	context "context"
	model "ozon_test_task/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinkService is a mock of LinkService interface.
type MockLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceMockRecorder
}

// MockLinkServiceMockRecorder is the mock recorder for MockLinkService.
type MockLinkServiceMockRecorder struct {
	mock *MockLinkService
}

// NewMockLinkService creates a new mock instance.
func NewMockLinkService(ctrl *gomock.Controller) *MockLinkService {
	mock := &MockLinkService{ctrl: ctrl}
	mock.recorder = &MockLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkService) EXPECT() *MockLinkServiceMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockLinkService) CreateShortURL(ctx context.Context, link *model.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockLinkServiceMockRecorder) CreateShortURL(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockLinkService)(nil).CreateShortURL), ctx, link)
}

// GetBaseURL mocks base method.
func (m *MockLinkService) GetBaseURL(ctx context.Context, link *model.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseURL", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseURL indicates an expected call of GetBaseURL.
func (mr *MockLinkServiceMockRecorder) GetBaseURL(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseURL", reflect.TypeOf((*MockLinkService)(nil).GetBaseURL), ctx, link)
}
